import { selectLegalAuthorities, type LegalAuthority } from "./legalLibrary";
import { analyzeTemporalCase, type CaseLegalAnalysis } from "./legalCaseAnalysis";

export interface SelectedRecordData { comparendo:string; fecha:string; organismo:string; estado:string; valor:string; placa?:string; cedula?:string; codigo?:string; nombre?:string; correo?:string; fechaResolucion?:string; fechaNotificacion?:string; fechaMandamientoPago?:string; fechaNotificacionMandamiento?:string; fechaEjecutoria?:string; huboAudiencia?:boolean|string; existeResolucion?:boolean|string; actuacionesCobro?:string; }
export type LegalRoute="CADUCIDAD"|"PRESCRIPCION"|"PERDIDA_EJECUTORIEDAD"|"NOTIFICACION"|"DEBIDO_PROCESO"|"FOTODETECCION"|"REVOCATORIA_DIRECTA";
export type LegalCertainty="CONFIGURADO"|"NO_CONFIGURADO"|"HIPOTESIS_OBJETIVA"|"INDETERMINADO";
export interface LegalAssessment { routes:LegalRoute[]; primaryRoute:LegalRoute|null; priority:"alta"|"media"|"baja"; missingEvidence:string[]; reasoning:string[]; certainty?:LegalCertainty; temporal?:CaseLegalAnalysis; }
export interface DynamicLegalQuestion { id:string; label:string; type:"text"|"date"|"select"|"textarea"; required?:boolean; options?:{label:string;value:string}[]; route:LegalRoute; }
export interface LegalDraft { hechos:string; solicitudConcreta:string; fundamentos:string; assessment:LegalAssessment; authorities:LegalAuthority[]; document:string; }

const OCR_FALLBACK="No identificado en el documento aportado";
const OCR_GARBAGE=/,,|,m|\bk,,\b/i;
export function sanitizeValue(value:string|undefined):string { if(value===undefined)return OCR_FALLBACK; const v=String(value).replace(/\s+/g," ").trim(); const letters=(v.match(/[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]/g)||[]).length; return !v||OCR_GARBAGE.test(v)||letters<2?OCR_FALLBACK:v; }
function truthy(v:unknown){return v===true||["si","sí","true","1"].includes(String(v??"").trim().toLowerCase());}
function normalized(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
function sanctioned(r:SelectedRecordData){const s=normalized(String(r.estado||""));const id=String(r.comparendo||"").trim().toUpperCase();return Boolean(/-SA(?:$|[-_\s])/i.test(id)||r.fechaResolucion||truthy(r.existeResolucion)||truthy(r.huboAudiencia))||["multa","sancion","sancionado","pendiente de pago","cobro coactivo","cobro","mandamiento","acuerdo de pago","pagada","pagado","cancelada","cancelado"].some(w=>s.includes(normalized(w)));}
function parseDate(v?:string|null):Date|null{if(!v)return null;const x=String(v).trim(),m=x.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/),iso=m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:x.slice(0,10),d=new Date(`${iso}T00:00:00Z`);return Number.isNaN(d.getTime())?null:d;}
function longDate(v?:string|null){const d=parseDate(v);return d?new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(d):(v||"fecha no acreditada");}
function todayUTC(){const d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));}
function temporalConclusion(t:CaseLegalAnalysis):string{if(!t.initialExpiryDate)return "No existe una fecha inicial suficientemente acreditada para realizar un cómputo temporal confiable.";const expiry=parseDate(t.initialExpiryDate),today=todayUTC();if(expiry&&expiry>today)return `No se encuentra actualmente configurado el vencimiento del término inicial de tres años. El término se proyecta hasta el ${longDate(t.initialExpiryDate)}. La revisión del expediente resulta necesaria para determinar si existe una actuación sancionatoria, si la obligación es actualmente exigible y si eventualmente se produjo un mandamiento de pago cuya notificación tenga incidencia en el cómputo.`;if(expiry&&expiry<=today)return `Existe un vencimiento temporal objetivo que obliga a determinar si antes del ${longDate(t.initialExpiryDate)} se produjo una actuación interruptiva jurídicamente eficaz y, particularmente, si el mandamiento de pago fue notificado dentro del término.`;return t.temporalConclusion;}
function cleanRecord(r:SelectedRecordData):SelectedRecordData{return {...r,nombre:sanitizeValue(r.nombre),cedula:sanitizeValue(r.cedula),correo:sanitizeValue(r.correo),organismo:sanitizeValue(r.organismo),placa:sanitizeValue(r.placa)};}

export function assessTrafficRecord(input:SelectedRecordData):LegalAssessment{const r=cleanRecord(input),routes:LegalRoute[]=[],missing:string[]=[],reasoning:string[]=[],temporal=analyzeTemporalCase(r),isSanctioned=sanctioned(r),code=normalized(String(r.codigo||""));if(isSanctioned)reasoning.push("El registro presenta elementos compatibles con una multa o sanción; el análisis se concentra en acto sancionatorio, notificación, firmeza, exigibilidad, prescripción, cobro y fuerza ejecutoria.");else{routes.push("CADUCIDAD");missing.push("Expediente, decisión sancionatoria y constancia de ejecutoria, si existen.");}if(temporal.initialExpiryDate){routes.push("PRESCRIPCION");reasoning.push(temporalConclusion(temporal));missing.push(...temporal.evidenceQuestions.filter(x=>/mandamiento|cobro|prescrip/i.test(x)));}if(r.fechaMandamientoPago){routes.push("PERDIDA_EJECUTORIEDAD");missing.push("Constancia de notificación del mandamiento y actuaciones posteriores de cobro.");}if(!r.fechaNotificacion||!r.fechaNotificacionMandamiento){routes.push("NOTIFICACION");missing.push("Constancias de notificación de la orden de comparendo, resolución, recursos y mandamiento de pago, con fecha, medio, destinatario y soporte.");}if(/fotodeteccion|fotomulta|c35|d02|camara/.test(code)){routes.push("FOTODETECCION");missing.push("Evidencia de detección, prueba técnica y soportes de identificación del infractor.");}routes.push("DEBIDO_PROCESO","REVOCATORIA_DIRECTA");const unique=[...new Set(routes)];const primary=unique.includes("PERDIDA_EJECUTORIEDAD")?"PERDIDA_EJECUTORIEDAD":unique.includes("PRESCRIPCION")?"PRESCRIPCION":unique.includes("CADUCIDAD")?"CADUCIDAD":unique.includes("FOTODETECCION")?"FOTODETECCION":unique.includes("NOTIFICACION")?"NOTIFICACION":"REVOCATORIA_DIRECTA";const priority=unique.includes("PRESCRIPCION")||unique.includes("PERDIDA_EJECUTORIEDAD")?"alta":unique.includes("CADUCIDAD")||unique.includes("FOTODETECCION")||unique.includes("NOTIFICACION")?"media":"baja";return{routes:unique,primaryRoute:primary,priority,missingEvidence:[...new Set(missing)],reasoning:[...new Set(reasoning)],certainty:temporal.certainty,temporal};}

export function getDynamicLegalQuestions(record:SelectedRecordData,assessment:LegalAssessment):DynamicLegalQuestion[]{const q:DynamicLegalQuestion[]=[];const add=(x:DynamicLegalQuestion)=>{if(q.length<4&&!q.some(y=>y.id===x.id))q.push(x);};if(assessment.routes.includes("PRESCRIPCION")&&!record.fechaNotificacionMandamiento)add({id:"fecha_notificacion_mandamiento",label:"¿Tienes la fecha en que te notificaron el mandamiento de pago?",type:"date",route:"PRESCRIPCION"});if(assessment.routes.includes("PRESCRIPCION")&&!record.fechaMandamientoPago)add({id:"existe_mandamiento_pago",label:"¿Sabes si alguna vez te notificaron un mandamiento de pago por esta multa?",type:"select",route:"PRESCRIPCION",options:[{label:"Sí",value:"si"},{label:"No",value:"no"},{label:"No lo sé",value:"no_se"}]});if(assessment.routes.includes("NOTIFICACION"))add({id:"forma_notificacion",label:"¿Recibiste alguna comunicación o notificación relacionada con esta multa?",type:"select",route:"NOTIFICACION",options:[{label:"Sí",value:"si"},{label:"No",value:"no"},{label:"No lo sé",value:"no_se"}]});if(assessment.routes.includes("PERDIDA_EJECUTORIEDAD"))add({id:"actuaciones_cobro",label:"¿Conoces alguna actuación de cobro posterior al mandamiento, como embargo, acuerdo de pago o pago?",type:"textarea",route:"PERDIDA_EJECUTORIEDAD"});return q;}

function authorityBlock(a:LegalAuthority):string{let application=a.application?.trim()||"";if(a.id==="L769-159")application="La regla anterior resulta relevante porque el punto controvertido no es simplemente la antigüedad del comparendo, sino determinar si la administración realizó dentro del término las actuaciones necesarias y, en materia de cobro, cuándo fue efectivamente notificado el mandamiento de pago. El precedente citado por el Consejo de Estado permite exigir que esa cronología sea demostrada documentalmente por la autoridad.";return [`${a.source}, ${a.provision}: ${a.rule.trim()}`,a.development?.trim(),application?`En el caso concreto, ${application.replace(/\.$/,"")}.`:"",a.precedent?`Jurisprudencia aplicada: ${a.precedent.trim()}`:""].filter(Boolean).join("\n\n");}
function factsBlock(r:SelectedRecordData,t:CaseLegalAnalysis){const facts=[`El Estado de Cuenta SIMIT aportado por el solicitante identifica la actuación No. ${sanitizeValue(r.comparendo)}, asociada a ${sanitizeValue(r.organismo)}, y registra como fecha del hecho el ${r.fecha||"no identificada"}.`,`La actuación aparece asociada al documento de identidad ${sanitizeValue(r.cedula)}.`,`La información disponible sobre la placa es: ${sanitizeValue(r.placa)}.`,`El valor reportado para la obligación es ${sanitizeValue(r.valor)}.`];if(r.codigo)facts.push(`El registro identifica la infracción con el código ${sanitizeValue(r.codigo)}.`);facts.push("El Estado de Cuenta aportado no contiene, por sí solo, información suficiente para identificar la resolución sancionatoria, su fecha de expedición o su ejecutoria.");if(r.fechaResolucion)facts.push(`Se reporta una resolución o acto sancionatorio de fecha ${r.fechaResolucion}; debe verificarse documentalmente su contenido y ejecutoria.`);if(r.fechaNotificacion)facts.push(`Se reporta una fecha de notificación (${r.fechaNotificacion}), pero debe verificarse qué actuación fue notificada y la constancia documental que la respalda.`);else facts.push("El Estado de Cuenta aportado no permite establecer la fecha ni el medio mediante el cual se habría notificado el acto sancionatorio.");if(r.fechaMandamientoPago)facts.push(`Se reporta un mandamiento de pago de fecha ${r.fechaMandamientoPago}; su notificación debe verificarse separadamente.`);else facts.push("No se encuentra acreditada en la información aportada la existencia o fecha de un mandamiento de pago.");if(r.fechaNotificacionMandamiento)facts.push(`Se reporta notificación del mandamiento de pago el ${r.fechaNotificacionMandamiento}; si la constancia es válida, esta fecha constituye el hito relevante para el nuevo cómputo.`);else facts.push("Tampoco se encuentra acreditada una fecha de notificación del mandamiento de pago. Esta ausencia no demuestra que la notificación jamás ocurrió, pero sí deja abierta una cuestión probatoria decisiva.");if(t.initialExpiryDate)facts.push(`Desde la fecha del hecho (${t.initialDate}) puede efectuarse el cómputo inicial de tres años, cuyo vencimiento calculado corresponde al ${t.initialExpiryDate}.`);return facts.map((x,i)=>`${i+1}. ${x}`).join("\n\n");}
function applicationBlock(r:SelectedRecordData,a:LegalAssessment){const t=a.temporal!, conclusion=temporalConclusion(t);const scenarios=t.initialExpiryDate?[`Si no existe una notificación válida del mandamiento de pago anterior al ${longDate(t.initialExpiryDate)}, existe un vencimiento temporal objetivo que obliga a establecer la consecuencia jurídica correspondiente.`,`Si se acredita que el mandamiento fue notificado válidamente antes del ${longDate(t.initialExpiryDate)}, debe analizarse el nuevo cómputo desde esa notificación y las actuaciones posteriores.`,`Si la primera notificación eficaz ocurrió después del ${longDate(t.initialExpiryDate)}, debe analizarse si el término ya había vencido antes de esa actuación.`]:[];return ["4.1. Norma aplicable y presupuesto jurídico",t.rules.join("\n\n")||"La norma aplicable debe confrontarse con la cronología que resulte probada.","4.2. Cómputo aplicado al caso concreto",t.executiveSummary,...t.inferences,"4.3. Actuaciones que pueden modificar el cómputo",t.mandamientoNotificationDate?`Se reporta notificación del mandamiento el ${t.mandamientoNotificationDate}. Debe verificarse su eficacia y reconstruirse el periodo posterior.`:"La fecha de notificación del mandamiento no está acreditada; por tanto, no puede asumirse una interrupción eficaz.","4.4. Hechos acreditados, inferencias y prueba pendiente",`Hechos acreditados:\n${t.facts.join("\n")||"No hay hechos temporales suficientes acreditados."}\n\nInferencias calculadas:\n${t.inferences.join("\n")||"No hay inferencias temporales confiables."}\n\nPrueba pendiente:\n${t.evidenceQuestions.join("\n")||"No se identifican pruebas temporales adicionales."}`,"4.5. Escenarios jurídicos",scenarios.join("\n\n")||"No es posible construir escenarios temporales confiables con la información disponible.","4.6. Conclusión jurídica",conclusion,"4.7. Jurisprudencia aplicada","La jurisprudencia pertinente se utiliza para resolver las cuestiones identificadas en este expediente y no como una lista bibliográfica aislada.","4.8. Conclusión probatoria","La ausencia de una constancia en el Estado de Cuenta no constituye por sí sola prueba de inexistencia de la actuación. Sí identifica una prueba crítica que debe ser aportada por la autoridad para sostener la cronología que pretenda hacer valer."].join("\n\n");}
function requestsBlock(r:SelectedRecordData,a:LegalAssessment){const t=a.temporal!,expiry=t.initialExpiryDate?longDate(t.initialExpiryDate):"el vencimiento del término aplicable";return [`1. Que se remita copia íntegra, legible y completa del expediente administrativo relacionado con la actuación No. ${sanitizeValue(r.comparendo)}.`,`2. Que se informe cuál fue el acto mediante el cual se impuso la sanción, indicando número, fecha, contenido y constancia de ejecutoria, y se remita copia íntegra.`,`3. Que se remitan las constancias de notificación de la orden de comparendo, acto sancionatorio, recursos y mandamiento de pago, indicando acto, destinatario, medio, fecha y soporte.`,`4. Que se informe si se adelantó audiencia, su fecha, acta, pruebas y decisión adoptada.`,`5. Que se informe si existe o existió proceso de cobro coactivo y se remitan sus actuaciones completas, incluyendo mandamiento, notificación y actuaciones posteriores, con sus fechas.`,`6. Que se determine expresamente si antes del ${expiry} se produjo una actuación interruptiva jurídicamente eficaz y, de ser así, cuál fue y cuándo fue notificada.`,`7. Que, si no se acredita una actuación interruptiva eficaz dentro del término aplicable y este ya se encontraba vencido, se adopte la consecuencia jurídica correspondiente respecto de la prescripción.`,`8. Que, si se acredita una actuación interruptiva anterior al vencimiento, se indique el nuevo cómputo y las actuaciones posteriores que sustentan la exigibilidad actual.`,`9. Que se determine, cuando corresponda, si existe pérdida de fuerza ejecutoria, irregularidad de notificación, vulneración del debido proceso, revocatoria directa u otra consecuencia jurídicamente procedente.`,`10. Que se emita respuesta de fondo, clara, congruente, motivada y completa frente a cada solicitud.`].join("\n\n");}

/** ÚNICA función de ensamblaje. Construye I–IX exactamente una vez. */
export function generateUnifiedLegalDocument(input:SelectedRecordData):LegalDraft{const r=cleanRecord(input),assessment=assessTrafficRecord(r),t=assessment.temporal!,authorities=selectLegalAuthorities(assessment.routes,`${r.estado||""} ${r.codigo||""}`),hechos=factsBlock(r,t),analysis=applicationBlock(r,assessment),requests=requestsBlock(r,assessment),conclusion=temporalConclusion(t);const document=["I. OBJETO",`Solicito la revisión integral de la situación jurídica de la actuación No. ${sanitizeValue(r.comparendo)}, con base en los datos acreditados, el cómputo temporal que puede realizarse y las actuaciones que la autoridad debe demostrar documentalmente.`,"II. ANTECEDENTES Y HECHOS",hechos,"III. PROBLEMA JURÍDICO","Debe determinarse, a partir de los hechos y documentos disponibles, cuál es la situación jurídica actual de la actuación, qué término resulta aplicable, cuál es su fecha inicial y de vencimiento, qué actuaciones pueden modificarlo y qué consecuencia corresponde según la evidencia acreditada.","IV. FUNDAMENTOS DE DERECHO",authorities.length?authorities.map(authorityBlock).join("\n\n"):"No se incorporará una cita normativa que no esté respaldada por la biblioteca jurídica controlada.","V. ANÁLISIS DEL CASO CONCRETO",analysis,"VI. RECONSTRUCCIÓN CRONOLÓGICA Y EFECTOS JURÍDICOS",t.events.map(e=>`${e.label}: ${e.date||"no acreditada"} [${e.status}]. ${e.legalEffect}`).join("\n\n")||"No existe una cronología suficiente para reconstruir el expediente.","VII. PRUEBA Y DOCUMENTOS NECESARIOS",t.evidenceQuestions.map(x=>`• ${x}`).join("\n")||"• Expediente administrativo completo.","VIII. CONCLUSIÓN JURÍDICA",conclusion,"IX. PETICIONES",requests].join("\n\n");return{hechos,solicitudConcreta:requests,fundamentos:document,assessment,authorities,document};}

/** Compatibilidad con consumidores existentes: delega al pipeline único. */
export function generateLegalDraft(input:SelectedRecordData):LegalDraft{return generateUnifiedLegalDocument(input);}
