import type { LegalAuthority } from './legalLibrary';

/**
 * Ampliación de la biblioteca jurídica de TrámiteYa.
 * Fuentes verificadas contra textos oficiales consultados el 28-08-2026.
 * Regla: estas autoridades sirven para construir análisis condicionados a la evidencia;
 * no deben convertirse en hechos del caso sin soporte documental.
 */
export const ADDITIONAL_TRAFFIC_LEGAL_LIBRARY: LegalAuthority[] = [
  {
    id: 'L1755-14',
    source: 'Ley 1755 de 2015',
    provision: 'Artículo 14',
    rule: 'Las peticiones deben resolverse, por regla general, dentro de quince días; las de documentos e información tienen término especial de diez días y las consultas de treinta días.',
    development: 'El término depende de la modalidad de la petición. Para solicitudes de expediente, copias y soportes de una actuación de tránsito debe identificarse la naturaleza documental de lo solicitado.',
    application: 'Permite estructurar solicitudes de expediente y exigir respuesta dentro del término legal correspondiente.',
    useWhen: ['derecho de petición', 'expediente', 'copias', 'documentos', 'información'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1755_2015.html',
  },
  {
    id: 'L1755-15',
    source: 'Ley 1755 de 2015',
    provision: 'Artículo 15',
    rule: 'Las peticiones pueden presentarse por medios idóneos de comunicación y transferencia de datos; ninguna autoridad puede negarse a recibir y radicar solicitudes respetuosas.',
    development: 'La radicación y trazabilidad son relevantes para demostrar la fecha de presentación y el contenido de la solicitud.',
    application: 'Refuerza la exigencia de constancia de radicación y permite diseñar el flujo de TrámiteYa para conservar evidencia de la solicitud.',
    useWhen: ['radicación', 'derecho de petición', 'correo', 'trazabilidad'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1755_2015.html',
  },
  {
    id: 'L1755-16',
    source: 'Ley 1755 de 2015',
    provision: 'Artículo 16',
    rule: 'La petición debe identificar autoridad, solicitante, objeto, razones y documentos que se desean aportar, entre otros elementos mínimos.',
    development: 'La suficiencia formal de la petición no exonera a la autoridad de examinar integralmente lo solicitado.',
    application: 'Sirve como checklist de calidad para los documentos generados por TrámiteYa.',
    useWhen: ['derecho de petición', 'estructura', 'requisitos formales'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1755_2015.html',
  },
  {
    id: 'L1755-24',
    source: 'Ley 1755 de 2015',
    provision: 'Artículo 24',
    rule: 'La reserva de información y documentos procede únicamente en los casos expresamente establecidos por la Constitución o la ley.',
    development: 'Una solicitud de expediente debe distinguir entre información accesible al interesado y documentos sometidos legalmente a reserva.',
    application: 'Permite formular solicitudes de copia del expediente evitando afirmaciones absolutas sobre documentos cuya reserva deba analizarse.',
    useWhen: ['expediente', 'documentos', 'reserva', 'copias'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1755_2015.html',
  },
  {
    id: 'CPACA-93',
    source: 'Ley 1437 de 2011 - CPACA',
    provision: 'Artículo 93',
    rule: 'Los actos administrativos pueden ser revocados por las autoridades en los supuestos legales, entre ellos cuando sean manifiestamente contrarios a la Constitución o la ley, cuando no estén conformes al interés público o social, o cuando causen agravio injustificado.',
    development: 'La revocatoria directa tiene causales y régimen propio; no debe utilizarse como sinónimo automático de nulidad, prescripción o caducidad.',
    application: 'Cuando la evidencia revele una causal legal de revocatoria, el motor puede incorporarla como ruta jurídica diferenciada.',
    useWhen: ['revocatoria directa', 'acto administrativo', 'ilegalidad', 'agravio injustificado'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1437_2011.html',
  },
  {
    id: 'L1843-7',
    source: 'Ley 1843 de 2017',
    provision: 'Artículo 7',
    rule: 'Cuando se demuestre que una orden de comparendo detectada mediante sistemas tecnológicos no fue notificada o fue indebidamente notificada, los términos para la reducción de la sanción comienzan a correr desde la notificación del comparendo.',
    development: 'La norma no autoriza a presumir la indebida notificación: exige demostrarla y relacionarla con sus efectos legales.',
    application: 'El motor debe solicitar la constancia de envío, entrega o devolución y solo después formular la consecuencia que corresponda.',
    useWhen: ['fotodetección', 'fotomulta', 'notificación', 'Ley 1843'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1843_2017.html',
  },
  {
    id: 'L1843-8',
    source: 'Ley 1843 de 2017',
    provision: 'Artículo 8',
    rule: 'En infracciones detectadas por ayudas tecnológicas, la autoridad debe observar el procedimiento legal de envío de la orden de comparendo y sus soportes, incluyendo el término de tres días hábiles previsto para el envío.',
    development: 'Debe distinguirse el deber de envío de la efectiva notificación y analizarse el expediente completo. La jurisprudencia constitucional ha desarrollado las garantías del procedimiento.',
    application: 'Activa preguntas probatorias sobre validación, fecha de envío, operador postal o medio electrónico, dirección RUNT, devolución y demás constancias.',
    precedent: 'Sentencia C-038 de 2020: la inexequibilidad recayó sobre la responsabilidad solidaria automática, no sobre el sistema de detección tecnológica como tal.',
    useWhen: ['fotodetección', 'fotomulta', 'cámara', 'notificación', 'validación'],
    url: 'https://www.secretariasenado.gov.co/senado/basedoc/ley_1843_2017.html',
  },
  {
    id: 'C530-2003',
    source: 'Corte Constitucional',
    provision: 'Sentencia C-530 de 2003',
    rule: 'La sanción de tránsito debe recaer sobre quien resulte jurídicamente responsable; la sola notificación al propietario no equivale automáticamente a demostrar que fue el infractor.',
    development: 'La jurisprudencia condicionó reglas del Código Nacional de Tránsito para preservar la personalidad de las sanciones y la defensa del propietario citado.',
    application: 'En fotodetección, el expediente debe mostrar cómo se vinculó al presunto infractor y qué elementos sustentan la imputación.',
    useWhen: ['fotodetección', 'propietario', 'conductor', 'culpabilidad', 'responsabilidad personal'],
    precedent: 'La Sentencia C-038 de 2020 recoge y desarrolla esta línea jurisprudencial.',
    url: 'https://www.corteconstitucional.gov.co/relatoria/2020/C-038-20.htm',
  },
  {
    id: 'C980-2010',
    source: 'Corte Constitucional',
    provision: 'Sentencia C-980 de 2010',
    rule: 'La notificación del comparendo al propietario cumple una función de citación y garantía de defensa; no convierte por sí sola al propietario en destinatario automático de la sanción.',
    development: 'La línea jurisprudencial distingue entre comunicar la infracción para permitir comparecencia y acreditar la responsabilidad sancionatoria.',
    application: 'Sirve para separar en el análisis la existencia de una comunicación al propietario de la prueba de responsabilidad personal.',
    useWhen: ['fotodetección', 'notificación al propietario', 'responsabilidad'],
    url: 'https://www.corteconstitucional.gov.co/relatoria/2022/C-321-22.htm',
  },
  {
    id: 'C038-2020',
    source: 'Corte Constitucional',
    provision: 'Sentencia C-038 de 2020',
    rule: 'Fue declarada inexequible la responsabilidad solidaria sancionatoria del propietario por infracciones detectadas tecnológicamente cuando no se exige imputación personal y culpabilidad.',
    development: 'La decisión no eliminó el sistema de fotodetección; eliminó la solidaridad sancionatoria automática incompatible con responsabilidad personal, culpabilidad y debido proceso.',
    application: 'El motor debe utilizarla para preguntar quién fue identificado, qué conducta se imputó, qué prueba existe y cómo se garantizó defensa, evitando afirmar automáticamente que el propietario debe ser exonerado sin revisar el expediente.',
    useWhen: ['fotodetección', 'fotomulta', 'propietario', 'conductor', 'culpabilidad', 'debido proceso'],
    url: 'https://www.corteconstitucional.gov.co/relatoria/2020/C-038-20.htm',
  },
  {
    id: 'T051-2016',
    source: 'Corte Constitucional',
    provision: 'Sentencia T-051 de 2016',
    rule: 'La comunicación del procedimiento contravencional y las garantías de defensa son relevantes en casos de fotocomparendos; la tutela, sin embargo, está sujeta a sus propios requisitos de procedencia.',
    development: 'La providencia no debe citarse como si hubiera ordenado automáticamente anular toda fotomulta no notificada. Debe analizarse el caso concreto y la vía judicial disponible.',
    application: 'Sirve como apoyo para exigir prueba de la comunicación y del trámite, sin convertir la sentencia en una regla automática de nulidad.',
    useWhen: ['fotodetección', 'notificación', 'debido proceso', 'tutela'],
    url: 'https://www.corteconstitucional.gov.co/relatoria/autos/2018/a024-18.htm',
  },
  {
    id: 'C321-2022',
    source: 'Corte Constitucional',
    provision: 'Sentencia C-321 de 2022',
    rule: 'Reitera que la sola notificación del comparendo al propietario no lo convierte automáticamente en responsable; la sanción requiere vinculación formal y establecimiento de culpabilidad cuando la infracción lo exige.',
    development: 'La sentencia diferencia el deber de comparecer o ejercer defensa de la atribución sancionatoria y debe leerse junto con el régimen específico de cada infracción.',
    application: 'Fortalece el módulo de individualización del infractor y evita que el motor confunda propietario, citado y responsable sancionatorio.',
    useWhen: ['fotodetección', 'propietario', 'culpabilidad', 'responsabilidad personal'],
    url: 'https://www.corteconstitucional.gov.co/relatoria/2022/C-321-22.htm',
  },
];
