import type { FormAnswers } from '../types/form';
export type LegalRule={id:string;label:string;description:string;applies:(answers:FormAnswers)=>boolean;instruction:string};
export type TrafficDecision={id:string;label:string;level:'favorable'|'possible'|'insufficient';reason:string;nextStep:string;legalBasis:string[]};
const getDate=(a:FormAnswers,k:string)=>{const v=a[k];if(!v)return null;const d=new Date(String(v)+'T00:00:00');return Number.isNaN(d.getTime())?null:d};
const ageDays=(a:FormAnswers,k:string)=>{const d=getDate(a,k);return d?Math.floor((Date.now()-d.getTime())/86400000):null};
const cause=(a:FormAnswers)=>String(a.causal_principal??a.causal??'').toLowerCase();
export const trafficRules:LegalRule[]=[
{id:'prescripcion',label:'Prescripción',description:'Revisión del término de prescripción de la sanción y de una eventual interrupción por mandamiento de pago.',applies:a=>cause(a).includes('prescrip'),instruction:'Verificar fecha del hecho, existencia y notificación del mandamiento de pago y demás actuaciones de cobro.'},
{id:'caducidad',label:'Caducidad',description:'Revisión del término legal para decidir la imposición de la sanción.',applies:a=>cause(a).includes('caduc'),instruction:'Verificar fecha del hecho, fecha de audiencia/decisión y régimen temporal aplicable.'},
{id:'fotomulta',label:'Fotodetección',description:'Revisión de identificación, notificación, evidencia y trámite de detección tecnológica.',applies:a=>/foto|fotomult|detecci[oó]n/i.test(cause(a)+' '+String(a.hechos??'')),instruction:'Solicitar evidencia de detección, identificación, notificación y actuaciones administrativas.'},
{id:'notificacion',label:'Notificación y debido proceso',description:'Revisión de constancias de notificación y oportunidades de defensa.',applies:a=>cause(a).includes('notific'),instruction:'Solicitar constancias completas de envío, entrega o notificación y verificar oportunidad de defensa.'},
{id:'correccion',label:'Corrección de identificación o registro',description:'Revisión de inconsistencias en datos, placa, persona o registro.',applies:a=>cause(a).includes('correc'),instruction:'Contrastar el dato cuestionado con los documentos oficiales y solicitar corrección expresa.'},
{id:'soportes',label:'Solicitud de soportes',description:'Pedir copia de los documentos que sustentan la actuación.',applies:()=>true,instruction:'Solicitar copia íntegra del comparendo, evidencia, notificaciones, actos administrativos y soportes pertinentes.'},
];
export function getApplicableTrafficRules(answers:FormAnswers){return trafficRules.filter(r=>r.applies(answers));}
export function evaluateTrafficCase(a:FormAnswers):TrafficDecision[]{
 const out:TrafficDecision[]=[];const d=ageDays(a,'fecha_comparendo');const mand=ageDays(a,'fecha_mandamiento_pago');const audiencia=getDate(a,'fecha_audiencia');const c=cause(a);
 if(c.includes('prescrip')){if(mand!==null)out.push({id:'prescripcion',label:'Prescripción: requiere verificación del cobro',level:'possible',reason:'Se suministró una fecha de mandamiento de pago; debe verificarse su notificación y sus efectos sobre el término.',nextStep:'Solicitar copia del mandamiento de pago y constancia de notificación.',legalBasis:['Ley 769 de 2002, art. 159']});else if(d!==null&&d>=1095)out.push({id:'prescripcion',label:'Prescripción: indicio favorable',level:'favorable',reason:'Han transcurrido al menos tres años desde la fecha del hecho indicada y no se informó mandamiento de pago.',nextStep:'Solicitar declaración de prescripción y soportes completos de cobro.',legalBasis:['Ley 769 de 2002, art. 159']});else out.push({id:'prescripcion',label:'Prescripción: información insuficiente',level:'insufficient',reason:'No han transcurrido tres años desde la fecha suministrada o falta información relevante sobre cobro.',nextStep:'Obtener expediente y constancias de cobro antes de afirmar la prescripción.',legalBasis:['Ley 769 de 2002, art. 159']});}
 if(c.includes('caduc')){if(audiencia)out.push({id:'caducidad',label:'Caducidad: verificar audiencia/decisión',level:'possible',reason:'Existe fecha de audiencia. Debe compararse con el hecho y con el régimen temporal aplicable.',nextStep:'Solicitar acta de audiencia, decisión sancionatoria y recursos.',legalBasis:['Ley 769 de 2002, art. 161']});else if(d!==null&&d>=365)out.push({id:'caducidad',label:'Caducidad: indicio favorable',level:'favorable',reason:'Ha transcurrido al menos un año desde el hecho y no se informó audiencia efectiva.',nextStep:'Solicitar expediente y verificar si dentro del término legal se decidió la imposición de la sanción.',legalBasis:['Ley 769 de 2002, art. 161']});else out.push({id:'caducidad',label:'Caducidad: información insuficiente',level:'insufficient',reason:'Faltan fechas relevantes o aún no ha transcurrido un año desde el hecho.',nextStep:'Completar fechas y obtener el expediente administrativo.',legalBasis:['Ley 769 de 2002, art. 161']});}
 if(/foto|fotomult|detecci[oó]n/.test(c))out.push({id:'fotomulta',label:'Fotodetección: revisión reforzada',level:'possible',reason:'La procedencia depende de evidencia, identificación, notificación y demás actuaciones del expediente.',nextStep:'Solicitar evidencia, constancias de notificación, acto sancionatorio y trazabilidad del trámite.',legalBasis:['Ley 1843 de 2017','Ley 769 de 2002']});
 if(c.includes('notific'))out.push({id:'notificacion',label:'Notificación: revisar expediente',level:'possible',reason:'Una irregularidad de notificación puede afectar el ejercicio oportuno de defensa, pero debe acreditarse documentalmente.',nextStep:'Obtener las constancias completas de notificación.',legalBasis:['Constitución Política, art. 29','Ley 769 de 2002']});
 if(c.includes('correc'))out.push({id:'correccion',label:'Corrección: verificar inconsistencia',level:'possible',reason:'La solicitud debe contrastar el dato cuestionado con documentos oficiales.',nextStep:'Adjuntar soporte de la inconsistencia y solicitar corrección expresa.',legalBasis:['Ley 769 de 2002']});
 return out;
}
