export interface TransitAuthority {
  municipio: string;
  departamento: string;
  nombreOficial: string;
  keywords: string[];
}

function normalize(value: string): string {
  return value.replace(/\d{2}:\d{2}:\d{2}/g, '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

export function findMatchingAuthority(rawText: string): string | undefined {
  if (!rawText) return undefined;
  const cleanText = normalize(rawText);
  const candidates = [...TRANSIT_AUTHORITIES].sort((a, b) => Math.max(...b.keywords.map((k) => normalize(k).length)) - Math.max(...a.keywords.map((k) => normalize(k).length)));
  for (const auth of candidates) {
    for (const kw of auth.keywords) {
      const cleanKw = normalize(kw);
      if (cleanKw && cleanText.includes(cleanKw)) return auth.nombreOficial;
    }
  }
  return undefined;
}

export const TRANSIT_AUTHORITIES: TransitAuthority[] = [
  { municipio: 'Sibaté', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE SIBATÉ', keywords: ['sibaté', 'sitate'] },
  { municipio: 'Bogotá', departamento: 'Cundinamarca', nombreOficial: 'SECRETARIA DISTRITAL DE BOGOTÁ - CONSORCIO SIM', keywords: ['bogotá', 'bogota'] },
  { municipio: 'La Calera', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE LA CALERA', keywords: ['la calera'] },
  { municipio: 'Chía', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE MOVILIDAD MUNICIPAL DE CHÍA', keywords: ['chía', 'chia'] },
  { municipio: 'Cajicá', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE CAJICÁ', keywords: ['cajicá', 'cajica'] },
  { municipio: 'Cota', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE COTA', keywords: ['cota'] },
  { municipio: 'Facatativá', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE FACATATIVÁ', keywords: ['facatativá', 'facatativa'] },
  { municipio: 'Itagüí', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE ITAGÜÍ', keywords: ['itagüí', 'itagui'] },
  { municipio: 'Medellín', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE MEDELLÍN', keywords: ['medellín', 'medellin'] },
  { municipio: 'Sabanagrande', departamento: 'Atlántico', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL ATLÁNTICO SEDE SABANAGRANDE', keywords: ['sabanagrande'] },
  { municipio: 'Ubaté', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE UBATÉ', keywords: ['ubaté', 'ubate'] },
  { municipio: 'Acacías', departamento: 'Meta', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DE ACACIAS', keywords: ['acacías', 'acacias'] },
  { municipio: 'Guamal', departamento: 'Meta', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL META SEDE GUAMAL', keywords: ['guamal'] },
  { municipio: 'Pasto', departamento: 'Nariño', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PASTO', keywords: ['pasto'] },
  { municipio: 'Tangua', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE TANGUA', keywords: ['tangua'] },
  { municipio: 'Sincelejo', departamento: 'Sucre', nombreOficial: 'SECRETARÍA DE MOVILIDAD Y SEGURIDAD VIAL DE SINCELEJO', keywords: ['sincelejo'] },
  { municipio: 'El Cerrito', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE EL CERRITO', keywords: ['el cerrito'] },
  { municipio: 'Guacarí', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE GUACARÍ', keywords: ['guacarí', 'guacari'] },
  { municipio: 'Puerto Berrío', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN DE TRÁNSITO DE PUERTO BERRIO', keywords: ['puerto berrío', 'puerto berrio'] },
  { municipio: 'Saravena', departamento: 'Arauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SARAVENA', keywords: ['saravena'] },
  { municipio: 'El Carmen de Bolívar', departamento: 'Bolívar', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRANSPORTE Y TRÁNSITO DE EL CARMEN DE BOLÍVAR', keywords: ['el carmen de bolívar', 'el carmen de bolivar'] },
  { municipio: 'Aguachica', departamento: 'Cesar', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE AGUACHICA', keywords: ['aguachica'] },
  { municipio: 'El Banco', departamento: 'Magdalena', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE EL BANCO', keywords: ['el banco'] },
  { municipio: 'Imués', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE IMUÉS', keywords: ['imués', 'imues'] },
  { municipio: 'Túquerres', departamento: 'Nariño', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE TUQUERRES', keywords: ['túquerres', 'tuquerres'] },
  { municipio: 'Fresno', departamento: 'Tolima', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE FRESNO', keywords: ['fresno'] },
  { municipio: 'Guadalajara de Buga', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE GUADALAJARA DE BUGA', keywords: ['guadalajara de buga'] },
  { municipio: 'Tuluá', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE TULUÁ', keywords: ['tuluá', 'tulua'] },
  { municipio: 'Magangué', departamento: 'Bolívar', nombreOficial: 'FONDO MUNICIPAL DE TRÁNSITO Y TRANSPORTE TERRESTRE DE MAGANGUÉ', keywords: ['magangué', 'magangue'] },
  { municipio: 'Chiquinquirá', departamento: 'Boyacá', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE CHIQUINQUIRÁ', keywords: ['chiquinquirá', 'chiquinquira'] },
  { municipio: 'Moniquirá', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 5 - MONIQUIRÁ', keywords: ['moniquirá', 'moniquira'] },
  { municipio: 'Saboyá', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 4 - SABOYA', keywords: ['saboyá', 'saboya'] },
  { municipio: 'Riosucio', departamento: 'Caldas', nombreOficial: 'SUBSECRETARÍA DE MOVILIDAD DE RIOSUCIO', keywords: ['riosucio'] },
  { municipio: 'Hatonuevo', departamento: 'La Guajira', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DE LA GUAJIRA SEDE HATONUEVO', keywords: ['hatonuevo'] },
  { municipio: 'Maicao', departamento: 'La Guajira', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE MAICAO', keywords: ['maicao'] },
  { municipio: 'Buesaco', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE BUESACO', keywords: ['buesaco'] },
  { municipio: 'Armenia', departamento: 'Quindío', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE ARMENIA', keywords: ['armenia'] },
  { municipio: 'La Tebaida', departamento: 'Quindío', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE LA TEBAIDA', keywords: ['la tebaida'] },
  { municipio: 'Barbosa', departamento: 'Santander', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE BARBOSA', keywords: ['barbosa'] },
  { municipio: 'Charalá', departamento: 'Santander', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DE CHARALÁ', keywords: ['charalá', 'charala'] },
  { municipio: 'Caucasia', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE CAUCASIA', keywords: ['caucasia'] },
  { municipio: 'Frontino', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO MUNICIPAL DE FRONTINO', keywords: ['frontino'] },
  { municipio: 'Aránzazu', departamento: 'Caldas', nombreOficial: 'UNIDAD DE TRÁNSITO DE CALDAS SEDE ARÁNZAZU', keywords: ['ará nzazu', 'aranzazu'] },
  { municipio: 'Chinchiná', departamento: 'Caldas', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE CHINCHINÁ', keywords: ['chinchiná', 'chinchina'] },
  { municipio: 'Salamina', departamento: 'Caldas', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE SALAMINA', keywords: ['salamina'] },
  { municipio: 'Riohacha', departamento: 'La Guajira', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE RIOHACHA', keywords: ['riohacha'] },
  { municipio: 'Sitionuevo', departamento: 'Magdalena', nombreOficial: 'SECRETARIA DE TRÁNSITO Y TRANSPORTE DEL MAGDALENA SEDE SITIO NUEVO', keywords: ['sitionuevo', 'sitio nuevo'] },
  { municipio: 'Cúcuta', departamento: 'Norte de Santander', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE CÚCUTA', keywords: ['cúcuta', 'cucuta'] },
  { municipio: 'Los Patios', departamento: 'Norte de Santander', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DEL MUNICIPIO DE LOS PATIOS', keywords: ['los patios'] },
  { municipio: 'Santa Rosa de Cabal', departamento: 'Risaralda', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y GOBIERNO MUNICIPAL DE SANTA ROSA DE CABAL', keywords: ['santa rosa de cabal'] },
  { municipio: 'Palmira', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE PALMIRA', keywords: ['palmira'] },
  { municipio: 'Santa Fe de Antioquia', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO MUNICIPAL DE SANTAFÉ DE ANTIOQUIA', keywords: ['santafé de antioquia', 'santa fe de antioquia'] },
  { municipio: 'Cartagena', departamento: 'Bolívar', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO TRÁNSITO Y TRANSPORTE DISTRITAL DE CARTAGENA', keywords: ['cartagena'] },
  { municipio: 'Nobsa', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 2 - NOBSA', keywords: ['nobsa'] },
  { municipio: 'Sogamoso', departamento: 'Boyacá', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SOGAMOSO', keywords: ['sogamoso'] },
  { municipio: 'Sahagún', departamento: 'Córdoba', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SAHAGÚN', keywords: ['sahagún', 'sahagun'] },
  { municipio: 'Fundación', departamento: 'Magdalena', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE FUNDACIÓN', keywords: ['fundación', 'fundacion'] },
  { municipio: 'Villavicencio', departamento: 'Meta', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE VILLAVICENCIO', keywords: ['villavicencio'] },
  { municipio: 'Samaniego', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE SAMANIEGO', keywords: ['samaniego'] },
  { municipio: 'Calarcá', departamento: 'Quindío', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE CALARCÁ', keywords: ['calarcá', 'calarca'] },
  { municipio: 'Circasia', departamento: 'Quindío', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO DEL QUINDÍO SEDE CIRCASIA', keywords: ['circasia'] },
  { municipio: 'Buenaventura', departamento: 'Valle del Cauca', nombreOficial: 'SUBSECRETARÍA DE REGULACIÓN Y CONTROL DE TRÁNSITO Y TRANSPORTE DE BUENAVENTURA', keywords: ['buenaventura'] },
  { municipio: 'Andes', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE ANDES', keywords: ['andes'] },
  { municipio: 'Cómbita', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 1 - COMBITA', keywords: ['cómbita', 'combita'] },
  { municipio: 'Paipa', departamento: 'Boyacá', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PAIPA', keywords: ['paipa'] },
  { municipio: 'Manzanares', departamento: 'Caldas', nombreOficial: 'DIRECCIÓN MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE MANZANARES', keywords: ['manzanares'] },
  { municipio: 'Florencia', departamento: 'Caquetá', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE FLORENCIA', keywords: ['florencia'] },
  { municipio: 'Guachucal', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE GUACHUCAL', keywords: ['guachucal'] },
  { municipio: 'Mocoa', departamento: 'Putumayo', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE MOCOA', keywords: ['mocoa'] },
  { municipio: 'Málaga', departamento: 'Santander', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE MÁLAGA', keywords: ['málaga', 'malaga'] },
  { municipio: 'Espinal', departamento: 'Tolima', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE ESPINAL', keywords: ['espinal'] },
  { municipio: 'Guamo', departamento: 'Tolima', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DEL TOLIMA SEDE GUAMO', keywords: ['guamo'] },
  { municipio: 'Copacabana', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE COPACABANA', keywords: ['copacabana'] },
  { municipio: 'San Andrés', departamento: 'Archipiélago de San Andrés, Providencia', nombreOficial: 'DIRECCIÓN DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DE SAN ANDRES ISLA', keywords: ['san andres isla', 'san andrés isla'] },
  { municipio: 'El Paujil', departamento: 'Caquetá', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL CAQUETÁ SEDE EL PAUJIL', keywords: ['el paujil'] },
  { municipio: 'Montería', departamento: 'Córdoba', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRANSPORTE Y TRÁNSITO DE MONTERÍA', keywords: ['montería', 'monteria'] },
  { municipio: 'Garzón', departamento: 'Huila', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE GARZÓN', keywords: ['garzón', 'garzon'] },
  { municipio: 'Santa Marta', departamento: 'Magdalena', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE SANTA MARTA', keywords: ['santa marta'] },
  { municipio: 'Quimbaya', departamento: 'Quindío', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE QUIMBAYA', keywords: ['quimbaya'] },
  { municipio: 'Floridablanca', departamento: 'Santander', nombreOficial: 'DIRECCIÓN DE TRÁNSITO Y TRANSPORTE DE FLORIDABLANCA', keywords: ['floridablanca'] },
  { municipio: 'Piedecuesta', departamento: 'Santander', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y MOVILIDAD DE PIEDECUESTA', keywords: ['piedecuesta'] },
  { municipio: 'Carepa', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE CAREPA', keywords: ['carepa'] },
  { municipio: 'La Unión', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE LA UNIÓN', keywords: ['la unión'] },
  { municipio: 'Soatá', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 7 - SOATA', keywords: ['soatá', 'soata'] },
  { municipio: 'Chocontá', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE CHOCONTÁ', keywords: ['chocontá', 'choconta'] },
  { municipio: 'Orito', departamento: 'Putumayo', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE ORITO', keywords: ['orito'] },
  { municipio: 'San Gil', departamento: 'Santander', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE SAN GIL', keywords: ['san gil'] },
  { municipio: 'Socorro', departamento: 'Santander', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE SOCORRO', keywords: ['socorro'] },
  { municipio: 'Ortega', departamento: 'Tolima', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DEL TOLIMA SEDE ORTEGA', keywords: ['ortega'] },
  { municipio: 'Pradera', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PRADERA', keywords: ['pradera'] },
  { municipio: 'Roldanillo', departamento: 'Valle del Cauca', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE ROLDANILLO', keywords: ['roldanillo'] },
  { municipio: 'Apartadó', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRANSPORTE Y TRÁNSITO DE APARTADO', keywords: ['apartadó', 'apartado'] },
  { municipio: 'Barbosa', departamento: 'Antioquia', nombreOficial: 'DIRECCIÓN DE TRANSPORTE Y TRÁNSITO MUNICIPAL DE BARBOSA', keywords: ['barbosa'] },
  { municipio: 'Girardota', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE GIRARDOTA', keywords: ['girardota'] },
  { municipio: 'Turbo', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO DE TURBO', keywords: ['turbo'] },
  { municipio: 'Anserma', departamento: 'Caldas', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE ANSERMA', keywords: ['anserma'] },
  { municipio: 'Puerto Tejada', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE PUERTO TEJADA', keywords: ['puerto tejada'] },
  { municipio: 'Puerto Asís', departamento: 'Putumayo', nombreOficial: 'INSTITUTO MUNICIPAL DE TRANSPORTE Y MOVILIDAD DE PUERTO ASÍS', keywords: ['puerto asís', 'puerto asis'] },
  { municipio: 'Armero Guayabal', departamento: 'Tolima', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DEL TOLIMA SEDE ARMERO GUAYABAL', keywords: ['armero guayabal'] },
  { municipio: 'Líbano', departamento: 'Tolima', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE LÍBANO', keywords: ['líbano', 'libano'] },
  { municipio: 'Jamundí', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE JAMUNDÍ', keywords: ['jamundí', 'jamundi'] },
  { municipio: 'Sonsón', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SONSÓN', keywords: ['sonsón', 'sonson'] },
  { municipio: 'Ramiriquí', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 11 - RAMIRIQUI', keywords: ['ramiriquí', 'ramiriqui'] },
  { municipio: 'Tunja', departamento: 'Boyacá', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE TUNJA', keywords: ['tunja'] },
  { municipio: 'Caloto', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE CALOTO', keywords: ['caloto'] },
  { municipio: 'Santander de Quilichao', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SANTANDER DE QUILICHAO', keywords: ['santander de quilichao'] },
  { municipio: 'Lorica', departamento: 'Córdoba', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE LORICA', keywords: ['lorica'] },
  { municipio: 'El Zulia', departamento: 'Norte de Santander', nombreOficial: 'SECRETARÍA DE TRÁNSITO DEPARTAMENTAL DE NORTE DE SANTANDER SEDE EL ZULIA', keywords: ['el zulia'] },
  { municipio: 'Villa del Rosario', departamento: 'Norte de Santander', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRANSPORTES Y TRÁNSITO DE VILLA DEL ROSARIO', keywords: ['villa del rosario'] },
  { municipio: 'La Virginia', departamento: 'Risaralda', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE LA VIRGINIA', keywords: ['la virginia'] },
  { municipio: 'San Vicente de Chucurí', departamento: 'Santander', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE SAN VICENTE CHUCURI', keywords: ['san vicente de chucurí', 'san vicente de chucuri'] },
  { municipio: 'La Ceja', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN DE TRÁNSITO MUNICIPAL DE LA CEJA', keywords: ['la ceja'] },
  { municipio: 'Villa de Leyva', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 10 - VILLA DE LEYVA', keywords: ['villa de leyva'] },
  { municipio: 'Aguadas', departamento: 'Caldas', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE AGUADAS', keywords: ['aguadas'] },
  { municipio: 'Piendamó', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PIENDAMO', keywords: ['piendamó', 'piendamo'] },
  { municipio: 'Popayán', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE POPAYÁN', keywords: ['popayán', 'popayan'] },
  { municipio: 'Pitalito', departamento: 'Huila', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DE PITALITO', keywords: ['pitalito'] },
  { municipio: 'Timaná', departamento: 'Huila', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DEPARTAMENTAL DEL HUILA SEDE TIMANA', keywords: ['timaná', 'timana'] },
  { municipio: 'Tumaco', departamento: 'Nariño', nombreOficial: 'SECRETARÍA DE TRÁNSITO DISTRITAL DE TUMACO', keywords: ['tumaco'] },
  { municipio: 'Vélez', departamento: 'Santander', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE VÉLEZ', keywords: ['vélez', 'velez'] },
  { municipio: 'Purificación', departamento: 'Tolima', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DEL TOLIMA SEDE PURIFICACIÓN', keywords: ['purificación', 'purificacion'] },
  { municipio: 'La Unión', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE LA UNIÓN', keywords: ['la unión'] },
  { municipio: 'Marinilla', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DEL MUNICIPIO DE MARINILLA', keywords: ['marinilla'] },
  { municipio: 'Rionegro', departamento: 'Antioquia', nombreOficial: 'SUBSECRETARÍA DE MOVILIDAD, TRANSITO Y TRANSPORTE DE RIONEGRO', keywords: ['rionegro'] },
  { municipio: 'Puerto Boyacá', departamento: 'Boyacá', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PUERTO BOYACA', keywords: ['puerto boyacá', 'puerto boyaca'] },
  { municipio: 'San Vicente del Caguán', departamento: 'Caquetá', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL CAQUETÁ SEDE SAN VICENTE DEL CAGUÁN', keywords: ['san vicente del caguán', 'san vicente del caguan'] },
  { municipio: 'El Tambo', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE EL TAMBO', keywords: ['el tambo'] },
  { municipio: 'Timbío', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE TIMBÍO', keywords: ['timbío', 'timbio'] },
  { municipio: 'Planeta Rica', departamento: 'Córdoba', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRANSPORTE Y TRÁNSITO DE PLANETA RICA', keywords: ['planeta rica'] },
  { municipio: 'Inírida', departamento: 'Guainía', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE INÍRIDA', keywords: ['inírida', 'inirida'] },
  { municipio: 'Palermo', departamento: 'Huila', nombreOficial: 'UNIDAD MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE PALERMO', keywords: ['palermo'] },
  { municipio: 'Ciénaga', departamento: 'Magdalena', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE CIÉNAGA', keywords: ['ciénaga', 'cienaga'] },
  { municipio: 'Cartago', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE CARTAGO', keywords: ['cartago'] },
  { municipio: 'Guarne', departamento: 'Antioquia', nombreOficial: 'AGENCIA DE SEGURIDAD VIAL DE ANTIOQUIA SEDE GUARNE', keywords: ['guarne'] },
  { municipio: 'Manizales', departamento: 'Caldas', nombreOficial: 'SECRETARÍA DE TRANSPORTES Y TRÁNSITO MUNICIPAL DE MANIZALES', keywords: ['manizales'] },
  { municipio: 'Villamaría', departamento: 'Caldas', nombreOficial: 'UNIDAD DE TRÁNSITO DE CALDAS SEDE VILLAMARÍA', keywords: ['villamaría', 'villamaria'] },
  { municipio: 'Belén de los Andaquíes', departamento: 'Caquetá', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL CAQUETÁ SEDE BELÉN DE LOS ANDAQUIES', keywords: ['belén de los andaquíes', 'belen de los andaquies'] },
  { municipio: 'Bolívar', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE BOLÍVAR', keywords: ['bolívar'] },
  { municipio: 'Patía', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE PATÍA', keywords: ['patía', 'patia'] },
  { municipio: 'Sandoná', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE SANDONÁ', keywords: ['sandoná', 'sandona'] },
  { municipio: 'Pamplona', departamento: 'Norte de Santander', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE PAMPLONA', keywords: ['pamplona'] },
  { municipio: 'Caicedonia', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE CAICEDONIA', keywords: ['caicedonia'] },
  { municipio: 'Sevilla', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE SEVILLA', keywords: ['sevilla'] },
  { municipio: 'Leticia', departamento: 'Amazonas', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO Y REGULACIÓN VIAL DE LETICIA', keywords: ['leticia'] },
  { municipio: 'Santa Rosa de Osos', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO MUNICIPAL DE SANTA ROSA DE OSOS', keywords: ['santa rosa de osos'] },
  { municipio: 'Yarumal', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE YARUMAL', keywords: ['yarumal'] },
  { municipio: 'Miraflores', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 9 - MIRAFLORES', keywords: ['miraflores'] },
  { municipio: 'Miranda', departamento: 'Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE MIRANDA', keywords: ['miranda'] },
  { municipio: 'Istmina', departamento: 'Chocó', nombreOficial: 'DIRECCIÓN DE TRANSPORTE Y TRÁNSITO DEPARTAMENTAL DEL CHOCO SEDE ISTMINA', keywords: ['istmina'] },
  { municipio: 'Ocaña', departamento: 'Norte de Santander', nombreOficial: 'SECRETARÍA DE MOVILIDAD Y TRÁNSITO DE OCAÑA', keywords: ['ocaña', 'ocana'] },
  { municipio: 'Puerto Carreño', departamento: 'Vichada', nombreOficial: 'FONDO DEPARTAMENTAL DE TRÁNSITO DEL VICHADA SEDE PUERTO CARREÑO', keywords: ['puerto carreño', 'puerto carreno'] },
  { municipio: 'Urrao', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE URRAO', keywords: ['urrao'] },
  { municipio: 'Garagoa', departamento: 'Boyacá', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE GARAGOA', keywords: ['garagoa'] },
  { municipio: 'Guateque', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 6 - GUATEQUE', keywords: ['guateque'] },
  { municipio: 'Quibdó', departamento: 'Chocó', nombreOficial: 'SECRETARÍA DE MOVILIDAD Y TRANSPORTE DE QUIBDO', keywords: ['quibdó', 'quibdo'] },
  { municipio: 'La Apartada', departamento: 'Córdoba', nombreOficial: 'SECRETARÍA DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DE CÓRDOBA SEDE LA APARTADA', keywords: ['la apartada'] },
  { municipio: 'El Rosal', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE EL ROSAL', keywords: ['el rosal'] },
  { municipio: 'Convención', departamento: 'Norte de Santander', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE CONVENCIÓN', keywords: ['convención', 'convencion'] },
  { municipio: 'Candelaria', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE CANDELARIA', keywords: ['candelaria'] },
  { municipio: 'Amalfi', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE AMALFI', keywords: ['amalfi'] },
  { municipio: 'Santa Rosa de Viterbo', departamento: 'Boyacá', nombreOficial: 'ITBOY - DISTRITO DE TRÁNSITO NO 3 - SANTA ROSA DE VITERBO', keywords: ['santa rosa de viterbo'] },
  { municipio: 'Cereté', departamento: 'Córdoba', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DE CERETE', keywords: ['cereté', 'cerete'] },
  { municipio: 'Cáqueza', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE CÁQUEZA', keywords: ['cáqueza', 'caqueza'] },
  { municipio: 'Corozal', departamento: 'Sucre', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE COROZAL', keywords: ['corozal'] },
  { municipio: 'Florida', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE FLORIDA', keywords: ['florida'] },
  { municipio: 'Santa Rosa', departamento: 'Bolívar', nombreOficial: 'SECRETARÍA DE MOVILIDAD DEL DEPARTAMENTO DE BOLÍVAR SEDE OPERATIVA SANTA ROSA NORTE', keywords: ['santa rosa norte'] },
  { municipio: 'La Dorada', departamento: 'Caldas', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE LA DORADA', keywords: ['la dorada'] },
  { municipio: 'Yopal', departamento: 'Casanare', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE YOPAL', keywords: ['yopal'] },
  { municipio: 'La Paz', departamento: 'Cesar', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE LA PAZ', keywords: ['la paz'] },
  { municipio: 'Chinú', departamento: 'Córdoba', nombreOficial: 'SECRETARÍA DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DE CÓRDOBA SEDE CHINÚ', keywords: ['chinú', 'chinu'] },
  { municipio: 'Fusagasugá', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE MOVILIDAD MUNICIPAL DE FUSAGASUGÁ', keywords: ['fusagasugá', 'fusagasuga'] },
  { municipio: 'Restrepo', departamento: 'Meta', nombreOficial: 'INSTITUTO DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DEL META SEDE RESTREPO', keywords: ['restrepo'] },
  { municipio: 'Sampués', departamento: 'Sucre', nombreOficial: 'DIRECCIÓN DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DE SUCRE (SEDE SAMPUÉS)', keywords: ['sampués', 'sampues'] },
  { municipio: 'Honda', departamento: 'Tolima', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE HONDA', keywords: ['honda'] },
  { municipio: 'Melgar', departamento: 'Tolima', nombreOficial: 'SECRETARÍA DE GOBIERNO, TRÁNSITO Y TRANSPORTE DE MELGAR', keywords: ['melgar'] },
  { municipio: 'Cali', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO DE CALI', keywords: ['cali'] },
  { municipio: 'Yumbo', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE YUMBO', keywords: ['yumbo'] },
  { municipio: 'Bello', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTES Y TRÁNSITO DE BELLO', keywords: ['bello'] },
  { municipio: 'Envigado', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE ENVIGADO', keywords: ['envigado'] },
  { municipio: 'Arjona', departamento: 'Bolívar', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRANSPORTE Y TRÁNSITO DE ARJONA', keywords: ['arjona'] },
  { municipio: 'Mompox', departamento: 'Bolívar', nombreOficial: 'INSPECCIÓN DE TRÁNSITO DE MOMPOX', keywords: ['mompox', 'mompós'] },
  { municipio: 'Turbaco', departamento: 'Bolívar', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE TURBACO', keywords: ['turbaco'] },
  { municipio: 'Duitama', departamento: 'Boyacá', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE DUITAMA', keywords: ['duitama'] },
  { municipio: 'Aguazul', departamento: 'Casanare', nombreOficial: 'DIRECCIÓN DEPARTAMENTAL DE TRÁNSITO, TRANSPORTE Y MOVILIDAD DE CASANARE SEDE AGUAZUL', keywords: ['aguazul'] },
  { municipio: 'Agustín Codazzi', departamento: 'Cesar', nombreOficial: 'SECRETARÍA DE TRANSPORTES Y TRÁNSITO MUNICIPAL DE AGUSTÍN CODAZZI', keywords: ['agustín codazzi', 'agustin codazzi'] },
  { municipio: 'Bosconia', departamento: 'Cesar', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DE BOSCONIA', keywords: ['bosconia'] },
  { municipio: 'Pacho', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE PACHO', keywords: ['pacho'] },
  { municipio: 'Villeta', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE VILLETA', keywords: ['villeta'] },
  { municipio: 'San José del Guaviare', departamento: 'Guaviare', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SAN JOSE DEL GUAVIARE', keywords: ['san jose del guaviare', 'san josé del guaviare'] },
  { municipio: 'Neiva', departamento: 'Huila', nombreOficial: 'SECRETARÍA DE INFRAESTRUCTURA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE NEIVA', keywords: ['neiva'] },
  { municipio: 'Rivera', departamento: 'Huila', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DEPARTAMENTAL DEL HUILA SEDE RIVERA', keywords: ['rivera'] },
  { municipio: 'Dosquebradas', departamento: 'Risaralda', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE DOSQUEBRADAS', keywords: ['dosquebradas'] },
  { municipio: 'Pereira', departamento: 'Risaralda', nombreOficial: 'INSTITUTO DE MOVILIDAD DE PEREIRA', keywords: ['pereira'] },
  { municipio: 'Alvarado', departamento: 'Tolima', nombreOficial: 'DEPARTAMENTO ADMINISTRATIVO DE TRÁNSITO Y TRANSPORTE DEL TOLIMA SEDE ALVARADO', keywords: ['alvarado'] },
  { municipio: 'Ibagué', departamento: 'Tolima', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE IBAGUÉ', keywords: ['ibagué', 'ibague'] },
  { municipio: 'Ciudad Bolívar', departamento: 'Antioquia', nombreOficial: 'INSPECCIÓN MUNICIPAL DE TRÁNSITO DE CIUDAD BOLÍVAR', keywords: ['ciudad bolívar', 'ciudad bolivar'] },
  { municipio: 'Galapa', departamento: 'Atlántico', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE GALAPA', keywords: ['galapa'] },
  { municipio: 'Puerto Colombia', departamento: 'Atlántico', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE PUERTO COLOMBIA', keywords: ['puerto colombia'] },
  { municipio: 'La Plata', departamento: 'Huila', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE LA PLATA', keywords: ['la plata'] },
  { municipio: 'Ipiales', departamento: 'Nariño', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE IPIALES', keywords: ['ipiales'] },
  { municipio: 'Pupiales', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE PUPIALES', keywords: ['pupiales'] },
  { municipio: 'Barrancabermeja', departamento: 'Santander', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE BARRANCABERMEJA', keywords: ['barrancabermeja'] },
  { municipio: 'Andalucía', departamento: 'Valle del Cauca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE ANDALUCÍA', keywords: ['andalucía', 'andalucia'] },
  { municipio: 'Zarzal', departamento: 'Valle del Cauca', nombreOficial: 'INSPECCIÓN DE TRÁNSITO Y TRANSPORTE DE ZARZAL', keywords: ['zarzal'] },
  { municipio: 'Caldas', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y TRÁNSITO DE CALDAS', keywords: ['caldas'] },
  { municipio: 'Sabaneta', departamento: 'Antioquia', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE SABANETA', keywords: ['sabaneta'] },
  { municipio: 'Arauca', departamento: 'Arauca', nombreOficial: 'INSTITUTO DE TRÁNSITO Y TRANSPORTE DEPARTAMENTAL DE ARAUCA', keywords: ['arauca'] },
  { municipio: 'Barranquilla', departamento: 'Atlántico', nombreOficial: 'SECRETARÍA DISTRITAL DE TRÁNSITO Y SEGURIDAD VIAL DE BARRANQUILLA', keywords: ['barranquilla'] },
  { municipio: 'Soledad', departamento: 'Atlántico', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE SOLEDAD', keywords: ['soledad'] },
  { municipio: 'Girardot', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE MUNICIPAL DE GIRARDOT', keywords: ['girardot'] },
  { municipio: 'Ricaurte', departamento: 'Cundinamarca', nombreOficial: 'SECRETARÍA DE TRANSPORTE Y MOVILIDAD DE CUNDINAMARCA SEDE RICAURTE', keywords: ['ricaurte'] },
  { municipio: 'Plato', departamento: 'Magdalena', nombreOficial: 'INSPECCIÓN DE TRÁNSITO DE PLATO', keywords: ['plato'] },
  { municipio: 'Granada', departamento: 'Meta', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO DE GRANADA', keywords: ['granada'] },
  { municipio: 'La Unión', departamento: 'Nariño', nombreOficial: 'SUBSECRETARÍA DE TRANSITO Y TRANSPORTE DEPARTAMENTAL DE NARIÑO SEDE LA UNION', keywords: ['la union'] },
  { municipio: 'Bucaramanga', departamento: 'Santander', nombreOficial: 'DIRECCIÓN DE TRÁNSITO Y TRANSPORTE DE BUCARAMANGA', keywords: ['bucaramanga'] },
  { municipio: 'Girón', departamento: 'Santander', nombreOficial: 'SECRETARÍA MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE GIRÓN', keywords: ['girón', 'giron'] },
  { municipio: 'Valledupar', departamento: 'Cesar', nombreOficial: 'INSTITUTO MUNICIPAL DE TRÁNSITO Y TRANSPORTE DE VALLEDUPAR', keywords: ['valledupar'] },
  { municipio: 'Sampués', departamento: 'Sucre', nombreOficial: 'DIRECCIÓN DEPARTAMENTAL DE TRÁNSITO Y TRANSPORTE DE SUCRE (SEDE SAMPUÉS)', keywords: ['sampués', 'sampues'] },
  { municipio: 'Sampués', departamento: 'Sucre', nombreOficial: 'SECRETARÍA DE TRÁNSITO Y TRANSPORTE DPTAL SUCRE - SAMPUÉS', keywords: ['dptal sucre'] },
];