"use client";

import React, { useEffect, useState } from "react";
import StepForm from "../../../../components/StepForm";
import Header from "../../../../components/Header";
import Footer from "../../../../components/Footer";
import { validateProcedureAnswers } from "../../../../lib/multitramiteEngine";
import { evaluateTrafficCase } from "../../../../lib/legalRules";
import { useRouter, useSearchParams } from "next/navigation";
import { localDraftStorage } from "../../../../lib/draftStorage";
import { procedureStorage } from "../../../../lib/procedureStorage";
import { getSupabaseBrowser } from "../../../../lib/supabaseBrowserClient";
import type { FormAnswers } from "../../../../types/form";
import { procedures } from "../../../../data/procedures";
import { getDynamicFormDefinition } from "../../../../data/dynamicForms";

export default function ProcedureForm({ params }: { params: { slug: string } }) {
  const [loading, setLoading] = useState(false); const [resetSignal, setResetSignal] = useState(0); const [instanceId, setInstanceId] = useState<string | undefined>(); const [remoteAnswers, setRemoteAnswers] = useState<FormAnswers | undefined>(); const [analysis, setAnalysis] = useState<any[]>([]); const [preview, setPreview] = useState<FormAnswers | null>(null);
  const router = useRouter(); const search = useSearchParams(); const definition = getDynamicFormDefinition(params.slug); const procedure = procedures.find((p) => p.slug === params.slug); const draftKey = `procedure:${params.slug}`;

  useEffect(() => { (async () => { try { const requested = search.get("instance"); const saved = localDraftStorage.load(draftKey) as any; const supabase = getSupabaseBrowser(); if (!supabase) return; const { data: { session } } = await supabase.auth.getSession(); if (!session?.user) return; let id = requested || saved?.data?.__instanceId; if (!id) { const r = await fetch("/api/instances", { headers: { Authorization: `Bearer ${session.access_token}` } }); if (r.ok) { const p = await r.json(); const existing = (p.data || []).find((i: any) => i.procedureSlug === params.slug && (i.status === "in_progress" || i.status === "draft")); if (existing) id = existing.id; } } if (!id) return; const r = await fetch(`/api/instances/${id}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (!r.ok) return; const i = await r.json(); setInstanceId(i.id); setRemoteAnswers(i.answers || {}); localDraftStorage.save(draftKey, { data: { ...(saved?.data || {}), ...(i.answers || {}), __instanceId: i.id }, savedAt: new Date().toISOString() }); } catch (e) { console.error(e); } })(); }, [search, draftKey, params.slug]);

  if (!definition || !procedure) return <main className="min-h-screen bg-slate-50"><Header/><section className="max-w-4xl mx-auto px-4 py-16"><h1 className="text-2xl font-bold">Trámite no disponible</h1></section><Footer/></main>;
  function analyze(a: FormAnswers) { const d = /multa|comparendo|fotomult|transito|tr[aá]nsito/i.test(`${params.slug} ${procedure.name} ${procedure.category}`) ? evaluateTrafficCase(a) : []; setAnalysis(d); return d; }
  async function ensureInstance(a: FormAnswers) { const s = getSupabaseBrowser(); const saved = localDraftStorage.load(draftKey) as any; if (s) { const { data: { session } } = await s.auth.getSession(); if (session?.user) { if (instanceId) { const r = await fetch(`/api/instances/${instanceId}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (r.ok) return r.json(); } const r = await fetch("/api/instances", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ procedureId: procedure.id, procedureSlug: procedure.slug, answers: a }) }); if (r.ok) { const x = await r.json(); setInstanceId(x.id); return x; } } } const id = saved?.data?.__instanceId; if (id) { const x = procedureStorage.get(id); if (x) return x; } const x = procedureStorage.create(procedure.id, procedure.slug, a); setInstanceId(x.id); return x; }
  async function generate(a: FormAnswers) { const issues = validateProcedureAnswers(procedure, a); if (issues.length) { alert(`Faltan ${issues.length} campo(s) obligatorio(s).`); return; } setLoading(true); try { const decisions = analyze(a); const instance = await ensureInstance(a); const enrichedAnswers = { ...a, __legalDecisionEngine: { version: 1, generatedAt: new Date().toISOString(), decisions } }; const r = await fetch("/api/documents/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ procedureSlug: procedure.slug, answers: enrichedAnswers, instanceId: instance.id }) }); if (!r.ok) throw new Error("Document generation failed"); const document = await r.json(); const s = getSupabaseBrowser(); if (s) { const { data: { session } } = await s.auth.getSession(); if (session?.user) await fetch(`/api/instances/${instance.id}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ answers: enrichedAnswers, status: "document_ready", document, completedAt: new Date().toISOString() }) }); } procedureStorage.update(instance.id, { answers: enrichedAnswers, status: "document_ready", document, completedAt: new Date().toISOString() }); localDraftStorage.remove(draftKey); router.push(`/tramites/${params.slug}/resultado/${instance.id}`); } catch (e) { console.error(e); alert("No fue posible generar el documento. Inténtalo nuevamente"); } finally { setLoading(false); } }

  return <main className="min-h-screen bg-slate-50 text-slate-900"><Header/><section className="max-w-4xl mx-auto px-4 py-12"><div className="bg-white p-6 md:p-8 rounded-2xl shadow"><div className="mb-6"><p className="text-sm font-medium text-blue-600">{procedure.category}</p><h1 className="text-2xl md:text-3xl font-bold mt-1">{definition.title}</h1><p className="text-slate-500 mt-2">Completa los datos. TrámiteYa adaptará el flujo según el trámite elegido.</p></div><div className="flex justify-end mb-4"><button onClick={() => { localDraftStorage.remove(draftKey); setInstanceId(undefined); setRemoteAnswers(undefined); setAnalysis([]); setPreview(null); setResetSignal(x => x + 1); }} className="px-3 py-1 rounded-md border text-sm">Borrar borrador</button></div>{!preview ? <StepForm steps={definition.steps} onComplete={a => { analyze(a); setPreview(a); }} draftKey={draftKey} resetSignal={resetSignal} instanceId={instanceId} onInstanceReady={setInstanceId} initialAnswers={remoteAnswers}/> : <div className="space-y-6"><div><p className="text-sm font-medium text-blue-600">Análisis preliminar</p><h2 className="text-2xl font-bold mt-1">Resultado de tu caso</h2><p className="text-sm text-slate-500 mt-2">Este resultado es preliminar y depende de la información suministrada.</p></div>{analysis.length ? analysis.map((d,i) => <div key={`${d.id}-${i}`} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-4"><strong>{d.label}</strong><span className="text-xs font-semibold uppercase">{d.level === "favorable" ? "Favorable" : d.level === "possible" ? "Requiere verificación" : "Información insuficiente"}</span></div><p className="text-sm text-slate-600 mt-2">{d.reason}</p><p className="text-sm mt-2"><strong>Siguiente actuación:</strong> {d.nextStep}</p></div>) : <div className="rounded-xl border p-4 text-sm text-slate-600">No se identificó una ruta jurídica concluyente con la información suministrada.</div>}<div className="flex gap-3 pt-2"><button onClick={() => setPreview(null)} className="px-4 py-2 rounded-md border">Editar respuestas</button><button onClick={() => generate(preview)} disabled={loading} className="px-4 py-2 rounded-md bg-blue-600 text-white font-semibold">{loading ? "Generando..." : "Generar documento"}</button></div></div>}{loading && <div className="mt-4 text-sm text-slate-500">Generando documento...</div>}</div></section><Footer/></main>;
}
