'use client';

import React, { FormEvent, KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';

type ComparendoContext = { numero?: string; fecha?: string; organismo?: string; municipio?: string; valor?: string | number; fechaResolucion?: string; fechaEjecutoria?: string; fechaMandamiento?: string; fechaNotificacionMandamiento?: string; placa?: string; codigoInfraccion?: string; estado?: string; documentNumber?: string; ownerName?: string };
type Message = { id: number; role: 'user' | 'assistant'; text: string };
type Answers = Record<string, string>;
type Question = { key: string; text: string; options?: string[]; when?: (c: ComparendoContext, a: Answers) => boolean };

const QUICK_REPLIES = ['💡 ¿Mi multa está prescrita?', '🏛️ ¿A dónde se envía este escrito?', '⚖️ ¿Qué pasa si me responden que NO?', '📑 ¿Qué significan los hechos de mi escrito?'];
const DRAFT_KEY = 'tramiteya:draft:procedure:derecho-de-peticion-eliminar-multa';
const SIMIT_SESSION_KEY = 'tramiteya:simit-upload:v1';
const TRAMI_ANSWERS_KEY = 'tramiteya:trami-questionnaire:v1';

// Solo identidad y hechos que pueden cambiar la estrategia. Trámi decide la figura jurídica.
const QUESTIONS: Question[] = [
  { key: 'identidad', text: 'Para que el documento salga correctamente a tu nombre: ¿tu **nombre completo** es el que aparece en tus datos?', options: ['✅ Sí, es correcto', '✏️ No, quiero corregirlo'], when: (_c, a) => !a.identidad },
  { key: 'nombreCorregido', text: 'Escríbeme tu **nombre completo**, tal como quieres que aparezca en el documento.', when: (_c, a) => a.identidad === '✏️ No, quiero corregirlo' && !a.nombreCorregido },
  { key: 'cedulaConfirmada', text: 'Tengo registrada la cédula **{cedula}** en el Estado de Cuenta. ¿Es correcta?', options: ['✅ Sí, es correcta', '✏️ No, quiero corregirla'], when: (c, a) => !!c.documentNumber && !a.cedulaConfirmada },
  { key: 'cedula', text: 'Escríbeme tu **número de cédula**.', when: (c, a) => !c.documentNumber || a.cedulaConfirmada === '✏️ No, quiero corregirla' },
  { key: 'correo', text: '¿Cuál es el **correo electrónico** donde quieres recibir la respuesta de la autoridad?', when: (_c, a) => !a.correo },
  { key: 'telefono', text: '¿Cuál es tu **número de teléfono**? Puedes responder “omitir”.', when: (_c, a) => !a.telefono },
  { key: 'notificacion', text: 'Ahora vamos al expediente: después de los hechos, ¿recibiste alguna **notificación de tránsito**?', options: ['❌ No recibí nada', '📩 Sí recibí algo', '🤷 No estoy seguro'] },
  { key: 'decision', text: '¿Alguna vez te informaron que existía una **resolución o decisión que impuso la multa**?', options: ['❌ No', '✅ Sí', '🤷 No lo recuerdo'] },
  { key: 'cobro', text: '¿La autoridad te ha **cobrado esta multa posteriormente**?', options: ['❌ Nunca', '💰 Sí, me han cobrado', '📄 Sí, recibí un mandamiento de pago', '🤷 No estoy seguro'] },
  { key: 'pago', text: '¿Has **pagado la multa o hecho un acuerdo de pago**?', options: ['❌ No', '💰 Sí, pagué', '🤝 Sí, hice un acuerdo', '🤷 No estoy seguro'] },
];

const clean = (v: unknown) => v == null ? undefined : String(v).trim() || undefined;
function readContext(): ComparendoContext | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = localStorage.getItem(DRAFT_KEY);
    if (raw) {
      const data = (JSON.parse(raw)?.data || {}) as Record<string, any>; const n = data.__simitRecord && typeof data.__simitRecord === 'object' ? data.__simitRecord : {};
      const c: ComparendoContext = { numero: clean(data.numero_comparendo || data.numero_acto || n.number), fecha: clean(data.fecha_comparendo || n.date), organismo: clean(data.autoridad || data.entidad || n.authority), municipio: clean(data.municipio || data.ciudad || n.municipality), valor: clean(data.valor ?? data.valor_multa ?? n.value), fechaResolucion: clean(data.fechaResolucion || n.resolutionDate), fechaEjecutoria: clean(data.fechaEjecutoria || n.executedDate), fechaMandamiento: clean(data.fechaMandamiento || n.mandamientoDate), fechaNotificacionMandamiento: clean(data.fechaNotificacionMandamiento || n.paymentOrderNotificationDate), placa: clean(data.placa || n.plate), codigoInfraccion: clean(data.codigoInfraccion || n.infractionCode), estado: clean(data.estadoComparendo || n.status), documentNumber: clean(data.documentNumber || data.numeroDocumento || data.documento || data.cedula || n.documentNumber), ownerName: clean(data.nombres && data.apellidos ? `${data.nombres} ${data.apellidos}` : n.ownerName) };
      if (c.numero || c.fecha) return c;
    }
    const s = JSON.parse(sessionStorage.getItem(SIMIT_SESSION_KEY) || '{}') as { records?: any[]; documentNumber?: string; selectedRecord?: any }; const r = s.selectedRecord || (s.records?.length === 1 ? s.records[0] : null); if (!r) return null;
    return { numero: clean(r.number), fecha: clean(r.date), organismo: clean(r.authority), municipio: clean(r.municipality), valor: clean(r.value), fechaResolucion: clean(r.resolutionDate), fechaEjecutoria: clean(r.executedDate), fechaMandamiento: clean(r.mandamientoDate || r.paymentOrderDate), fechaNotificacionMandamiento: clean(r.paymentOrderNotificationDate), placa: clean(r.plate), codigoInfraccion: clean(r.infractionCode), estado: clean(r.status), documentNumber: clean(s.documentNumber || r.documentNumber), ownerName: clean(r.ownerName) };
  } catch { return null; }
}
function readAnswers(): Answers { try { const p = JSON.parse(sessionStorage.getItem(TRAMI_ANSWERS_KEY) || '{}'); return p?.answers && typeof p.answers === 'object' ? p.answers : {}; } catch { return {}; } }
function saveAnswers(a: Answers, complete = false) { try { sessionStorage.setItem(TRAMI_ANSWERS_KEY, JSON.stringify({ version: 8, answers: a, complete, updatedAt: new Date().toISOString() })); } catch {} }
function renderText(text: string) { return text.split(/(\*\*[^*]+\*\*)/g).map((p, i) => p.startsWith('**') && p.endsWith('**') ? <strong key={i}>{p.slice(2, -2)}</strong> : <React.Fragment key={i}>{p}</React.Fragment>); }

export default function TramiWidget() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [context, setContext] = useState<ComparendoContext | null>(null); const [answers, setAnswers] = useState<Answers>({}); const [index, setIndex] = useState<number | null>(null); const [complete, setComplete] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const scrollRef = useRef<HTMLDivElement>(null); const initialized = useRef(false);
  const isTraffic = typeof window !== 'undefined' && window.location.pathname.includes('/formulario-simit');
  const questions = useMemo(() => QUESTIONS.filter(q => !q.when || q.when(context || {}, answers)), [context, answers]); const current = index == null ? null : questions[index]; const questionText = (q: Question) => q.text.replace('{cedula}', context?.documentNumber || answers.cedula || '');

  function start(c: ComparendoContext | null) {
    if (!c?.numero) return; const saved = readAnswers(); let meta: any = {}; try { meta = JSON.parse(sessionStorage.getItem(TRAMI_ANSWERS_KEY) || '{}'); } catch {}
    setContext(c); setAnswers(saved); setOpen(true); if (meta.complete) { setComplete(true); setIndex(null); return; } setComplete(false); setIndex(0);
    if (!Object.keys(saved).length) { const detected = c.documentNumber ? ` Ya detecté tu cédula **${c.documentNumber}**.` : ''; const name = c.ownerName ? ` También detecté el nombre **${c.ownerName}**.` : ''; setMessages([{ id: Date.now(), role: 'assistant', text: `Perfecto. Seleccionaste el comparendo **${c.numero}**${c.municipio ? ` · ${c.municipio}` : ''}.${detected}${name}\n\nNo tendrás más formularios. Te haré solo las preguntas indispensables y **yo determinaré la vía jurídica adecuada** con el expediente y tus respuestas.` }]); }
  }
  useEffect(() => { const refresh = () => { const c = readContext(); if (c?.numero) setContext(c); if (isTraffic && c?.numero && !initialized.current) { initialized.current = true; start(c); } }; refresh(); const restart = () => { initialized.current = false; setMessages([]); setAnswers({}); setComplete(false); setIndex(null); try { sessionStorage.removeItem(TRAMI_ANSWERS_KEY); } catch {} refresh(); }; window.addEventListener('trami:restart', restart); const t = window.setInterval(refresh, 700); return () => { window.clearInterval(t); window.removeEventListener('trami:restart', restart); }; }, [isTraffic]);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages, loading]);
  function add(text: string) { setMessages(m => [...m, { id: Date.now() + Math.random(), role: 'assistant', text }]); }
  function finish(a: Answers) { setComplete(true); setIndex(null); saveAnswers(a, true); add('Listo. **Ya tengo lo necesario.** Ahora cruzaré tu identidad, el SIMIT y la cronología. Tú no tienes que escoger entre caducidad, prescripción o pérdida de ejecutoriedad: **Trámi lo determina**.'); window.dispatchEvent(new CustomEvent('trami:questionnaire-complete', { detail: { answers: a, comparendo: context } })); }
  function answer(text: string) { if (!current || loading) return; const value = text.trim(); if (!value) return; const next = { ...answers, [current.key]: value }; if (current.key === 'cedulaConfirmada' && value.startsWith('✅')) next.cedula = context?.documentNumber || ''; if (current.key === 'nombreCorregido') next.identidad = value; if (current.key === 'telefono' && /^omitir$/i.test(value)) next.telefono = 'omitir'; setInput(''); setAnswers(next); saveAnswers(next); setMessages(m => [...m, { id: Date.now(), role: 'user', text: value }]); const rebuilt = QUESTIONS.filter(q => !q.when || q.when(context || {}, next)); const pos = rebuilt.findIndex(q => q.key === current.key); const ni = pos + 1; if (ni >= rebuilt.length) { finish(next); return; } setIndex(ni); window.setTimeout(() => add(questionText(rebuilt[ni])), 100); }
  async function send(text = input) { const value = text.trim(); if (!value || loading) return; if (index != null && !complete) { answer(value); return; } setInput(''); setMessages(m => [...m, { id: Date.now(), role: 'user', text: value }]); setLoading(true); try { const r = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: value, comparendo: context, answers }) }); const p = await r.json(); if (!r.ok) throw new Error(p.error || 'No fue posible responder.'); setMessages(m => [...m, { id: Date.now() + 1, role: 'assistant', text: p.text }]); } catch (e) { setMessages(m => [...m, { id: Date.now() + 1, role: 'assistant', text: e instanceof Error ? e.message : 'No fue posible responder.' }]); } finally { setLoading(false); } }
  function submit(e: FormEvent) { e.preventDefault(); void send(); } function onKey(e: KeyboardEvent<HTMLInputElement>) { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void send(); } }

  if (isTraffic && open) return <div className="fixed inset-0 z-[200] flex flex-col bg-slate-50">
    <header className="flex shrink-0 items-center justify-between bg-gradient-to-r from-indigo-700 via-violet-700 to-fuchsia-700 px-5 py-4 text-white shadow-lg"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15 text-2xl">🤖</div><div><div className="text-lg font-black">Trámi · Copiloto Legal</div><div className="flex items-center gap-1.5 text-xs text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-300"/> En línea · guiando tu trámite</div></div></div><button onClick={() => setOpen(false)} className="rounded-xl px-4 py-2 text-xl hover:bg-white/10" aria-label="Minimizar">─</button></header>
    <div className="border-b border-indigo-100 bg-white px-5 py-2.5 text-sm font-semibold text-indigo-800">📍 {context?.numero ? `Expediente: Comparendo ${context.numero}${context.municipio ? ` · ${context.municipio}` : ''}` : 'Preparando expediente…'}</div>
    <div ref={scrollRef} className="min-h-0 flex-1 overflow-y-auto px-4 py-6 md:px-8"><div className="mx-auto max-w-3xl space-y-4">
      {context?.numero && <div className="rounded-2xl border border-indigo-100 bg-white p-4 shadow-sm"><div className="text-xs font-bold uppercase tracking-wider text-indigo-500">Expediente seleccionado</div><div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><span><b>Comparendo:</b> {context.numero}</span><span><b>Fecha:</b> {context.fecha || 'pendiente'}</span><span><b>Cédula:</b> {context.documentNumber || answers.cedula || 'pendiente de confirmar'}</span></div></div>}
      {messages.map(m => <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-[15px] leading-6 shadow-sm ${m.role === 'user' ? 'bg-indigo-600 text-white' : 'border border-slate-200 bg-white text-slate-800'}`}>{renderText(m.text)}</div></div>)}
      {current && !complete && <div className="rounded-2xl border border-indigo-100 bg-indigo-50/70 p-4"><div className="mb-2 text-xs font-bold uppercase tracking-wider text-indigo-500">Trámi · pregunta indispensable</div><div className="text-[15px] font-semibold leading-6 text-slate-800">{renderText(questionText(current))}</div>{current.options && <div className="mt-3 flex flex-wrap gap-2">{current.options.map(o => <button key={o} type="button" onClick={() => answer(o)} disabled={loading} className="rounded-xl border border-indigo-200 bg-white px-3 py-2 text-sm font-semibold text-indigo-700 shadow-sm hover:border-indigo-400 hover:bg-indigo-50 disabled:opacity-50">{o}</button>)}</div>}</div>}
      {loading && <div className="text-sm text-slate-500">Trámi está analizando…</div>}
      {complete && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="text-lg font-black text-emerald-800">✅ Ya tengo lo necesario</div><p className="mt-1 text-sm leading-6 text-emerald-900">Voy a determinar la estrategia jurídica con la información disponible. No necesitas escoger la figura jurídica.</p><button type="button" onClick={() => window.dispatchEvent(new CustomEvent('trami:generate-document', { detail: { answers, comparendo: context } }))} className="mt-4 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white shadow hover:bg-indigo-700">🚀 Preparar mi documento</button></div>}
    </div></div>
    <div className="border-t bg-white px-4 py-3"><div className="mx-auto max-w-3xl"><div className="mb-2 flex gap-2 overflow-x-auto pb-1">{QUICK_REPLIES.map(q => <button key={q} type="button" onClick={() => send(q)} className="whitespace-nowrap rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100">{q}</button>)}</div><form onSubmit={submit} className="flex gap-2"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={onKey} placeholder={current ? 'Responde a Trámi…' : 'Pregúntale a Trámi…'} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none focus:border-indigo-500" disabled={loading}/><button className="rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-50" disabled={loading || !input.trim()}>➤</button></form></div></div>
  </div>;
  return <button type="button" onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-[190] flex items-center gap-2 rounded-full bg-gradient-to-r from-indigo-600 to-fuchsia-600 px-4 py-3 text-white shadow-xl"><span className="text-xl">🤖</span><span className="font-bold">Hablar con Trámi 🤖</span></button>;
}
