"use client";
import { useEffect, useState } from 'react';
export type CheckoutData = { publicKey: string; currency: 'COP'; amountInCents: number; reference: string; integrity: string; price: number; documentVersionId: string; instanceId?: string; accessToken?: string };
declare global { interface Window { WidgetCheckout?: new (config: any) => { open: (callback?: (result: any) => void) => void }; } }
export default function WompiCheckout({ procedureId, documentVersionId, instanceId, prefetchedConfig, onPending }: { procedureId: string; documentVersionId?: string; instanceId?: string; prefetchedConfig?: CheckoutData | null; onPending?: () => void }) {
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const lookup = instanceId || documentVersionId || '';
  useEffect(() => { if (document.getElementById('wompi-widget-script')) return; const script = document.createElement('script'); script.id = 'wompi-widget-script'; script.src = 'https://checkout.wompi.co/widget.js'; script.async = true; document.body.appendChild(script); }, []);
  async function waitForApproval(resolvedDocumentId: string): Promise<boolean> { for (let i = 0; i < 30; i += 1) { const response = await fetch(`/api/payments?procedureId=${encodeURIComponent(procedureId)}&instanceId=${encodeURIComponent(instanceId || '')}&documentVersionId=${encodeURIComponent(resolvedDocumentId)}`, { cache: 'no-store', headers: { 'x-guest-access-token': instanceId || resolvedDocumentId } }); if (response.ok) { const data = await response.json(); if (data.approved) return true; } await new Promise((resolve) => setTimeout(resolve, 1000)); } return false; }
  async function openCheckout() { setLoading(true); setError(null); onPending?.(); try { let data = prefetchedConfig; if (!data) { const response = await fetch('/api/payments/wompi', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-guest-access-token': instanceId || documentVersionId || '' }, body: JSON.stringify({ procedureId, instanceId: instanceId || undefined, documentVersionId: instanceId ? undefined : documentVersionId, amountInCents: 4990000, currency: 'COP' }) }); data = await response.json(); if (!response.ok) throw new Error((data as any).error || 'No fue posible preparar el pago.'); } if (!data) throw new Error('No fue posible preparar el pago.'); let attempts = 0; while (!window.WidgetCheckout && attempts < 30) { await new Promise((resolve) => setTimeout(resolve, 200)); attempts += 1; } if (!window.WidgetCheckout) throw new Error('No se pudo cargar el checkout de Wompi.'); const checkout = new window.WidgetCheckout({ currency: 'COP', amountInCents: 4990000, reference: data.reference, publicKey: data.publicKey, signature: { integrity: data.integrity } }); checkout.open(async (result: any) => { const status = String(result?.transaction?.status || '').toUpperCase(); if (status === 'APPROVED') { const approved = await waitForApproval(data!.documentVersionId); if (approved) { if (instanceId) localStorage.setItem(`tramiteya:paid-document:${instanceId}`, data!.documentVersionId); window.location.reload(); } else setError('El pago fue aprobado, pero estamos esperando la confirmación del servidor. Actualiza esta página en unos segundos.'); } else if (status === 'DECLINED' || status === 'ERROR' || status === 'VOIDED') setError('El pago no fue aprobado. Puedes intentarlo nuevamente.'); }); } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible iniciar el pago.'); } finally { setLoading(false); } }
  return <div className="space-y-2"><button type="button" onClick={openCheckout} disabled={loading || !lookup} className="w-full rounded-xl bg-gradient-to-r from-emerald-500 to-green-600 px-6 py-4 text-lg font-extrabold text-white shadow-lg shadow-emerald-200 transition-all hover:from-emerald-600 hover:to-green-700 active:scale-[0.98] focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:ring-offset-2 animate-pulse hover:animate-none">{loading ? 'Abriendo checkout…' : '🔓 DESBLOQUEAR Y DESCARGAR DOCUMENTO ($49.900 COP)'}</button>{error && <p className="text-xs text-red-600">{error}</p>}<p className="text-[11px] text-slate-400 text-center">Pago seguro procesado por Wompi. No necesitas crear una cuenta.</p></div>;
}
